### ISSUE TITLE
Central Admin People Picker not working correctly

### ISSUE THREAD

**Issue by julmsy** [Yvand/EntraCP#164]
Hello @Yvand,

I'm currently testing AzureCP on one of our SP2016 farm. I'm experiencing a strange behavior regarding the people picker from Central Administration. Below I describe all the steps I done to reproduce the scenario.

1. To start as clean I possible, I use the **Reset AzureCP configuration** button to start at initial phase.

2. Run a **PowerShell script to configure AzureCP** and add a new tenant.
```
Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")

$config.EnableAugmentation = $true
$config.FilterSecurityEnabledGroupsOnly = $true

$newAADTenant = New-Object azurecp.AzureTenant
$newAADTenant.Name = $j.AzureCP.AADTenantName
$newAADTenant.ApplicationId = $j.AzureCP.ApplicationId
$ExportableKeyStorageFlag = [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable
$newAADTenant.ClientCertificatePrivateKey = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($j.AzureCPCertificate.PFXPath, $j.AzureCPCertificate.PFXPassword,$ExportableKeyStorageFlag)
$newAADTenant.ExcludeGuests = $true
$config.AzureTenants.Add($newAADTenant)

$config.Update()
```

As you can see, I use an App Registration with Client certificate for authentication.

3. If I open the **Global configuration** page of AzureCP, the new tenant is added correctly. Note here: don't click on OK/Cancel button here, just leave the page by clicking on another Central Admin link.

4. Go to **Application Management**, and click on **Change site collection administrators**. Click on the **Browse** icon and type a user to find. Here I have systematically **No results** message.
From ULS log, I have the following:
```
[AzureCP] Unexpected error occurred while setting the certificate for tenant 'mapetiteentreprise.onmicrosoft.com'. Is the private key of the certificate exportable?: System.Security.Cryptography.CryptographicException: Keyset does not exist
[AzureCP] Unexpected error occurred in SearchOrValidate: System.Security.Cryptography.CryptographicException: Keyset does not exist
```

6. Now, go back to **Global configuration** page of AzureCP. Once open, just click on **OK** button.

7. Go back again to **Change site collection administrators** page, click on **Browse**, and type a user: it's works! (sometimes still not).

8. I proceed **iisreset**, reopen the **Change site collection administrators** page, and try to find again a user: it doesn't work anymore. No results at all, with the same errors in the ULS.

![image](https://user-images.githubusercontent.com/89072104/209140622-48a1442f-b878-4918-81dd-7bcb7d62dc37.png)

Directly on SharePoint site collection, no issue at all, the People Picker works well in all case.

To make it work again from Central Administration, the only way I've found for now is to remove the AAD tenant from the Global configuration page and recreate it. Not very fun...

I don't know if the ULS errors messages are relevant regarding the certificate private key, or it's a tree that hides the forest.
In all case, the certificate in question is on the Personal store, with permissions for the service account that manage the CA IIS Application.
Could you please check on your side if you can experience the same issue?
Or eventually, could you please advice?

Thanks!

**Comment by Yvand** [comment]
@julmsy thank you for reporting this.
I'll test your script to see if I can repro and keep you posted

**Comment by andikrueger** [comment]
This issue is caused by the account running the application pool of central admin not being able to access the certificate's private key. This can be fixed by adding the account to the certificate's private key reader group.

**Comment by andikrueger** [comment]
We are still facing this issue - even with the permissions on the private key. This kind of helped in the first run. It looks like a redeployment of the solutions breaks the access to the configuration.

**Comment by andikrueger** [comment]
@Yvand Within the solution there are two hardcoded passwords that are used to encrypt the certificate within the solutions scope. Would there be any other option available (like storing the certificate in the certificate store and enabling access for the web application account)? At the moment, it feels like a potential security risk to gain access to AAD.

**Comment by Yvand** [comment]
@andikrueger AzureCP needs to store the certificate and its private key in a location that can be accessed by all SharePoint processes, in all SharePoint server of the farm (because SharePoint may want to call AzureCP from anywhere).
With this contraint in mind, I found no better solution than storing the certificate and its private key in the persisted object, in the SharePoint configuration database, and this is also the reason why there are hardcoded passwords.
I'm totally open to discussions for a better implementation, but I don't see the Windows certificate store as a possible/easy solution, considering the pain it will be to ensure it is availalbe (and up to date) on all SharePoint servers.

**Comment by julmsy** [comment]
Hello @Yvand,

Thanks for clarification.
However, I don't see any constraint to deploy the PFX certificate to all SharePoint server of the farm and give access to the private key to the necessary services accounts.
From CA then, you give the Thumbprint of the certificate and password.

Currently when you deploy AzureCP you need to add azurecp.dll and its dependent assemblies + also configure the proxy for Internet access on all servers of the farm.
So deploying the certificate on all servers and give permissions access to the private key is not really a surprise finally and make sense.

**Comment by andikrueger** [comment]
If I'm not mistaken, then there would be no need to store the password for the private key of the certificate. We simple would assign the permissions to the account to be able to access the private key. 

And yes, it would be a manual step. On the other hand, this would allow for certain other management scenarios of renewing the certificate or pushing it from a central location to all servers that need access to this particular AAD application.

**Comment by Yvand** [comment]
Let me provide additional elements to feed this discussion:
The private key needs to be accessible to the following accounts (in all the servers of the SharePoint farm):
- SharePoint farm account
- All SharePoint application poool accounts
- SharePoint crawler account

AzureCP also stores the client secret of the app registration in clear text in the SharePoint config db.
I totally agree it is not great in terms of security, which relies on how well this database is secure (and it should be because it is a critical one).

Initially I wanted to use SharePoint itself to secure this sensitive data but I found no API for that.
For example, it would be really nice to use the farm passphrase to encrypt the sensitive data, but I found no way to do that.
And I cannot use a dumb SecureString, because multiple servers neeed to be able to decode it (and as far as I remember, SecureString cannot do that).

**Comment by julmsy** [comment]
Here is another typical scenario when AzureCP Claim Provider stop working from Central Administration: add or remove a Claim type mapping from Claim types configuration page. It will generate the ULS errors described in my first post.

Most of the time iisreset solve the issue, but I had one case where I had to completely recreate the tenant connection.

**Comment by Yvand** [comment]
@julmsy I do not repro this issue. Is there any error recorded in SharePoint logs when you repro this?

**Comment by julmsy** [comment]
Keep this open. Still facing issues, and will back soon on this topic.

**Comment by Yvand** [comment]
Could it depend on the account?
Do the web apps have a dedicated app pool account?
Does it work if you create a web app that uses the farm account?

**Comment by julmsy** [comment]
I've not finished all my tests, but could you try if you can repro this issue with the following configuration:
- SharePoint topology/config: not really matter from what I've seen.
- AzureCP tenant configuration: authentication with certificate.
- Have a dedicated SharePoint admin account (like a-yvand account that you use to remote your server)
- Open Central Admin with you a- account, and do some tests.

The complete test to done:
- Create a fresh site collection with only one admin user (sometimes at this point the people picker is not working)
- Once site collection created, still from CA, click Change site collection administrators
- Add a second site collection admin (if issue, you are getting a "The user does not exist or is not unique." error)

**Comment by julmsy** [comment]
Hi @Yvand,

Here is a real typical issue I'm having:
- I remote the SharePoint server with my personal admin account
- I opened 2 IE browser: one with my personal admin account, the second with the SP Farm account

![image](https://github.com/Yvand/AzureCP/assets/89072104/0143cc79-ce94-468c-ab3e-8e1509973ad0)
As you can see, on one case the Claim Provider is working, on the other, not.

I don't really explain this, but it's like if the first account/process that desarialize AzureCP have the "hand" on the certificate. Then if another account/process need to read the certificate and private key, there is an issue.

**Comment by Yvand** [comment]
@julmsy what is the error recorded in the SPS log when it does not work?

**Comment by julmsy** [comment]
Hi @Yvand,

The logs are the same as usual:
```
[AzureCP] Unexpected error occurred while setting the certificate for tenant 'xxx.onmicrosoft.com'. Is the private key of the certificate exportable?: System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.  , Callstack:   
 at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)    
 at System.Security.Cryptography.X509Certificates.X509Utils._ExportCertificatesToBlob(SafeCertStoreHandle safeCertStoreHandle, X509ContentType contentType, IntPtr password)    
 at System.Security.Cryptography.X509Certificates.X509Certificate.ExportHelper(X509ContentType contentType, Object password)    
 at azurecp.AzureTenant.set_ClientCertificatePrivateKey(X509Certificate2 value)
 
[AzureCP] Unexpected error occurred in SearchOrValidate: System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.  , Callstack:   
 at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)    
 at System.Security.Cryptography.X509Certificates.X509Utils._ExportCertificatesToBlob(SafeCertStoreHandle safeCertStoreHandle, X509ContentType contentType, IntPtr password)    
 at System.Security.Cryptography.X509Certificates.X509Certificate.ExportHelper(X509ContentType contentType, Object password)    
 at azurecp.AzureTenant.set_ClientCertificatePrivateKey(X509Certificate2 value)
 
[AzureCP] Validation failed: found 0 entities instead of 1 for incoming claim with value 'first.last@xxx.com' and type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'
```

Regarding permissions, my account is:
- Server and Farm admin
- dbo on SP Config DB

UAC is set on 'Never notify'.

For now I only did the tests from the SharePoint VM itself, I'll check if I can operate a test from another machine.

On your side, did you manage to repro this issue ?
So far, no problem with the secret authentication, this is really something related with certificate authentication.

**Comment by julmsy** [comment]
Interesting thing, but I was able to reverse the situation. With my account on the Central Admin I did:
- Remove the actual tenant configuration on AzureCP
- Add again the tenant
- iisreset
-> In this scenario, the claim provider works with my account, but NOT on the browser opened with the Farm account. This situation is valid for a time (1h? - token valid time), then it's not work anymore on my account.

From what I saw from the logs, the issue is not related with the process (w3wp.exe), neither the thread.

**Comment by andikrueger** [comment]
I used your arm template to create my environment. I have seen the same issue as described here.

it is an interesting thought about the account elevation and the context change. Still the issues appeared to be in the handling of the certificate which would be obtained from the configuration object.

**Comment by julmsy** [comment]
Ok, I did the test on my VMs, as I'm encountering the same issue.
So I confirm that if I open the Central Administration remotely from my SQL VM, I have exactly the same behavior:
- Works correctly if I open the browser with the Farm account
- KO with another account

Thanks @andikrueger for the confirmation, at least it confirm that is not related to our environments.
Have a nice vacation @Yvand 🏖️ !

**Comment by Yvand** [comment]
@julmsy I reproduce a similar exception but not in the central admin or the main web app, somehow I get it on the applicationPool "SharePoint Service Applications".
Interestingly, "SharePoint Service Applications" runs as spsvc, which is neither the central admin account of the web app account.

For the little I tested, it works fine on both the central admin and the main web app.
I tested on SharePoint Subscription May 2023 CU.
I'll continue the investigations on this issue.

**Comment by Yvand** [comment]
I made some progress but it is inconsistent:
Initially I installed Visual Studio and did live debug. At some point when I visit central admin > change site collection administrators, I see the following exception:

```
[AzureCP] Unexpected error occurred while getting access token for tenant 'M365x997769.onmicrosoft.com' on cloud instance 'AzurePublic': System.Security.Cryptography.CryptographicException: Access denied.  , Callstack:   
 at System.Security.Cryptography.NCryptNative.SetProperty(SafeNCryptHandle ncryptObject, String propertyName, Byte[] value, CngPropertyOptions propertyOptions)    
 at System.Security.Cryptography.CngKey.Open(SafeNCryptKeyHandle keyHandle, CngKeyHandleOpenOptions keyHandleOpenOptions)    
 at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(X509Certificate2 certificate)    
 at Microsoft.Identity.Client.PlatformsCommon.Shared.CryptographyManager.SignWithCertificate(String message, X509Certificate2 certificate)    
 at Microsoft.Identity.Client.Internal.JsonWebToken.Sign(X509Certificate2 certificate, String base64EncodedThumbprint, Boolean sendX5C)    
 at Microsoft.Identity.Client.Internal.ClientCredential.CertificateAndClaimsClientCredential.AddConfidentialClientParametersAsync(OAuth2Client oAuth2Client, ICoreLogger logger, ICryptographyManager cryptographyManager, String clientId, String tokenEndpoint, Boolean sendX5C, CancellationToken cancellationToken)    
 at Microsoft.Identity.Client.OAuth2.TokenClient.<AddBodyParamsAndHeadersAsync>d__7.MoveNext()  --- End of stack trace from previous location where exception was thrown ---    
[...] 
 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()    
 at azurecp.AADAppOnlyAuthenticationProvider.<GetAccessToken>d__14.MoveNext() in D:\a\1\s\AzureCP\AADAppOnlyAuthenticationProvider.cs:line 123
```

Using procmon (log attached) I saw many access denied for the central admin process (`spfarm` account is not local admin).
If I grant `spfarm` full control to either `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SystemCertificates` or `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\EnterpriseCertificates` and recycle, I get a different error:

```
[AzureCP] Unexpected error occurred while setting the certificate for tenant 'M365x997769.onmicrosoft.com'. Is the private key of the certificate exportable?: System.Security.Cryptography.CryptographicException: Keyset does not exist  , Callstack:   
 at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)    
 at System.Security.Cryptography.X509Certificates.X509Utils._ExportCertificatesToBlob(SafeCertStoreHandle safeCertStoreHandle, X509ContentType contentType, IntPtr password)    
 at System.Security.Cryptography.X509Certificates.X509Certificate.ExportHelper(X509ContentType contentType, Object password)    
 at azurecp.AzureTenant.set_ClientCertificatePrivateKey(X509Certificate2 value) in D:\a\1\s\AzureCP\AzureCPConfig.cs:line 759
```

The weird parts are:
- If I remove the permission on the registry keys, it keeps failing with the error `Keyset does not exist`, on each attempt
- I'm pretty sure that when I got the exception `CryptographicException: Access denied` only on 1st attempt, then people picker did return AAD results

Does this remotely match some of your tests?

**Comment by Yvand** [comment]
@andikrueger @julmsy I think I have fixed the certificate issues, through https://github.com/Yvand/AzureCP/commit/4f97d3517ab36cc93dcf4b789eff8f009089504c and https://github.com/Yvand/AzureCP/commit/fb6a28a26af6f2dbe31a5e37e06c526a12f77783.

Could you test the [latest nightly release](https://github.com/Yvand/AzureCP/releases/tag/nightly) and confirm if it works also for you?

**Comment by julmsy** [comment]
Thanks for the update @Yvand.
Yes, for sure! Will test it soon.

**Comment by julmsy** [comment]
So, for me it's all good. No more error at all regarding certificate.
Could you please explain a little bit the change/cause on this issue? You just change the way on how the certificate is added into the configDB ?

Last point: as this was the last of the last issues, do you intend to release a public version of AzureCP soon?

**Comment by Yvand** [comment]
@julmsy awesome, thank you for your feedback.
Basically I was inspired by https://support.microsoft.com/en-us/topic/kb5025823-change-in-how-net-applications-import-x-509-certificates-bf81c936-af2b-446e-9f7a-016f4713b46b
Then I read https://www.pkisolutions.com/handling-x509keystorageflags-in-applications/ and I much better understood what was happening in the code and the purpose of the flags.
So, in practice:
- I import the pfx from the SPS config database using EphemeralKeySet : https://github.com/Yvand/AzureCP/blob/06d91a9976da47db67b4f8a089f8a82e99fc0249/AzureCP/AzureCPConfig.cs#LL826C1-L826C82. With this flag, the cert cannot be exported (persisted) anywhere, and that is perfectly fine since it is only intended to be used in-memory.
- It is only when the certificate is selected by the administrator that it can be exported to SPS config database

Yes, publishing a release is high in my prio list. I'm currently actively working on updating my GitHub workflows to finish the migration from Azure DevOps, there is still work but I did the most difficult part
