### ISSUE TITLE
Azure CP connection disappears in SP 2019

### ISSUE THREAD

**Issue by mspilot54** [Yvand/EntraCP#186]
When the confiq wizard is ran on the cache servers, it removes the AzureCP connect in Central Admin.

**Comment by Yvand** [comment]
@mspilot54 it is surprising because both things are quite unrelated, is this something you reproduced more than once?

**Comment by vishnookumar** [comment]
My customer has been facing this problem since Jul 2022.. Every month, after patching we need to reapply the AzureCP configuration. we couldn't find the cause/ solution to this problem so far..

**Comment by vishnookumar** [comment]
> When the confiq wizard is ran on the cache servers, it removes the AzureCP connect in Central Admin.

Are you facing this issue during every config wizard run?

**Comment by Yvand** [comment]
@vishnookumar based on your description, it seems that the SharePoint config wizard deletes the AzureCP persisted object, which of course should not happen.
Do you know if this happens when a specific server runs the wizard? Or if any SharePoint server will trigger the issue?

**Comment by vishnookumar** [comment]
@Yvand We always run the wizard first on the central admin server & it triggers this issue always..

**Comment by mspilot54** [comment]
Hi there, it happens every time in all environments.  I think it only happens when I run the wizard on the cache server.

**Comment by Yvand** [comment]
> Hi there, it happens every time in all environments. I think it only happens when I run the wizard on the cache server.

@mspilot54, can you double check that the AzureCP assemblies are present in the GAC of this server?
A quick way to check that is to validate if you can load this assembly:

```powershell
Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
[azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")
```

**Comment by vishnookumar** [comment]
> > Hi there, it happens every time in all environments. I think it only happens when I run the wizard on the cache server.
> 
> @mspilot54, can you double check that the AzureCP assemblies are present in the GAC of this server? A quick way to check that is to validate if you can load this assembly:
> 
> ```powershell
> Add-Type -AssemblyName "AzureCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
> [azurecp.AzureCPConfig]::GetConfiguration("AzureCPConfig")
> ```

we ran this command, it is able to load the assembly and fetch the Azure CP config.

**Comment by Yvand** [comment]
Tbh I have no idea why SharePoint decides to delete the persisted object while doing the upgrade, I never saw this issue before...
I would encourage you to [migrate to EntraCP](https://entracp.yvand.net/blog/announcing-entracp/), but I don't know if it will fix this issue

**Comment by vishnookumar** [comment]
@Yvand when we move to EntraCP which is a different claim provider, do we need to re-run the user migration?

**Comment by Yvand** [comment]
@vishnookumar nope, this is not necessary because they generate the entities exactly the same way.

**Comment by KamilPacanek** [comment]
@vishnookumar @mspilot54 have you tried to fetch the EntraCP/Azure configuration directly from the SharePoint Config database (by using previously saved PersistenObjectId or simply `select * from [objects] where Name like '%CPConfig'`)? 
Do the `Status` and `Version` stay the same after executing Configuration Wizard?
