### ISSUE TITLE
Not showing migrated users.

### ISSUE THREAD

**Issue by Shafeeqts89** [Yvand/EntraCP#213]
Migrated user profiles from Windows authentication using **Move-SPUser**  cmdlet are not showing in the people picker.

**Comment by Yvand** [comment]
that is very little to start with, did you check the SharePoint logs and filter on product EntraCP to see what is happening?

**Comment by Shafeeqts89** [comment]
Yes, it is not hitting SharePoint hence no traces in the log. Basically, the suggestions are not popping up. When we save the form, the system attempts to resolve the user's name.

**Comment by Yvand** [comment]
I don't know what can cause this. Do you repro on a new site collection in same web app ?

**Comment by Shafeeqts89** [comment]
I don't think this is something related to the Entra CP, we can close this issue.
