### ISSUE TITLE
Cannot restrict EntraCP to only return Groups

### ISSUE THREAD

**Issue by NaveenKanukuntla** [Yvand/EntraCP#216]
### Discussed in https://github.com/Yvand/EntraCP/discussions/215

<div type='discussions-op-text'>

<sup>Originally posted by **NaveenKanukuntla** November 28, 2023</sup>
Here is my setup

1. EntraID as the directory lookup.
2. Utilizing EntraCP to fill claims for user on SharePoint 2016.
3. I already use Windows /Claims NTLM for user lookup from active directory.
4. Most of my security groups have been created in Azure and not in On-Prem AD.

Due to this, I would like to use EntraCP to lookup Security Groups in EntraID

Is it possible to limit my people picker results returned from EntraCP to only resolve/return role claims ?
</div>

**Comment by Yvand** [comment]
@NaveenKanukuntla please see my feedback in https://github.com/Yvand/EntraCP/discussions/215
