### ISSUE TITLE
"Edit" links fail to work on the "Claim types configuration" page

### ISSUE THREAD

**Issue by Yvand** [Yvand/EntraCP#219]
### Discussed in https://github.com/Yvand/EntraCP/discussions/218

<div type='discussions-op-text'>

<sup>Originally posted by **HermanGyorgy** December  7, 2023</sup>
Installed EntraCP 23.0.20231121 for testing purposes.  
In my test environment experience the below issue:  
 
"Edit" links fail to work on the "Claim types configuration" (/_admin/EntraCP/ClaimTypesConfig.aspx) page:
("Delete" links on the same page works OK.)

Edit link associated with below script:
javascript:Azurecp.ClaimsTablePage.EditItem('<n>')
<n>: is some index number

Error displayed on (F12) Developer Tools console tab:
SCRIPT5009: 'Azurecp' is undefined</div>

**Comment by jaycallahan1973** [comment]
I just installed this and am having the same issue.  EntraCP Shows up in people people but wont' look up anything and I was trying to make the Claims type the same as my AzureCP but it won't let me edit.

**Comment by Yvand** [comment]
@jaycallahan1973 what version exactly are you using?
