### ISSUE TITLE
EntraCP - Claim Types Configuration Edit link not working.

### ISSUE THREAD

**Issue by uday30980** [Yvand/EntraCP#222]
Hello Yvand,
Myself Uday from Canada.
We have used the AzureCP on our SP Server 2016 and its working fine. Now we are working on a project to migrate the SP site to new SP Server 2019. We have found in your article that there is a new EntraCP app available instead of AzureCP and so we have downloaded the EntraCP app and trying to install it for our initial testing along with migration the SP site that how People Picker behaving when compare to AzureCP with our existing configuration on old SP Server 2016.

We got an issue on EntraCP - Claims Type Configuration Page where we are unable to Edit the configuration. The Edit link not working at all.
<img width="875" alt="EntraCP_Claimstypeconfiguration_CentralAdmin" src="https://github.com/Yvand/EntraCP/assets/43591062/bfc78624-2018-4346-bd4d-88f478e1c4f1">
 We have checked the POP UP Blocker and all is good and we are still able to access the same edit on our AzureCP Claims type configuration page on Central Admin site.

I am attaching a screenshot of the EntraCP- Claims Type Configuration page for reference.
Any quick help /support from your side figuring out why the EDIT link is not working?

**Comment by Yvand** [comment]
Hello @uday30980, thank you for reporting this, I believe it duplicates issue https://github.com/Yvand/EntraCP/issues/219, which I already fixed but not released in a new version yet

**Comment by uday30980** [comment]
Thank you for your prompt response.
When will you plan to release a new version?

one more question?

do you have any reference articles to set a SP Server 2019 On-Prem User Profile Application Synchronization Service to the Azure AD with MFA federation SAML Simgle Sign On Authetication to set up . We have set the AzureAD as a TrustedIdentityIssuer and disabled the AD (Active directory domain) on the server. Through EntraCP or AzureCP we want to access the People Picker Search either through Mail or UPN and wanted to synchronize only AzureAD import under User Profile Service so that it will not duplicate the same users from our regular Windows AD as well as from AzureAD. ??

**Comment by Yvand** [comment]
@uday30980 a new release will not be in the very near future, but I expect it will be in less than 3 months.

Out of the box, SPS can import users only from AD (and with [additional config](https://joshroark.com/sharepoint-active-directory-import-with-trusted-provider-authentication-map-only-claim-user-identifier/), they can be mapped as trusted users).
But you cannot import directly from Entra ID, unless you develop something custom to do it

**Comment by uday30980** [comment]
I am trying to my default claimtype as UPN instead of email address and getting this error on Global Con

The SPTrustedLoginProvider 'AzureAD' is set with identity claim type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn', but is not set in claim types configuration list.
Please visit claim types configuration page to add it.

**Comment by uday30980** [comment]
Hi Yvand,

Everything is correctly set up on EntraCP and I am able to get a People Picker Working  but when i am trying to access the SP Site collection then i got the following error.

<img width="925" alt="ID4014" src="https://github.com/Yvand/EntraCP/assets/43591062/bd4f4a5e-9814-490b-b24b-d25f41669b0b">

D4014: A SecurityTokenHandler is not registered to read security token ('Assertion', 'urn:oasis:names:tc:SAML:2.0:assertion')
Exception Details: System.IdentityModel.Tokens.SecurityTokenException: ID4014: A SecurityTokenHandler is not registered to read security token ('Assertion', 'urn:oasis:names:tc:SAML:2.0:assertion').

Any suggestions?

**Comment by Yvand** [comment]
@uday30980 based on the error, SPS receives a SAML token 2.0, which it does not support:

- SPS (all versions) support SAML 1.1 token (not 2.0)
- SPS Subscription also supports ID tokens (through OIDC authentication)

EntraCP is not involved in this error that you reported
