### ISSUE TITLE
[Question] Remote authentication to SharePoint 2019 using EntraCP?

### ISSUE THREAD

**Issue by tahawkins21** [Yvand/EntraCP#224]
I have a SharePoint 2019 farm configured with EntraCP, and I want to use a python library such as Office365-REST-Python-Client to upload documents to a certain site collection from a separate web application. Supposedly this library supports on-premise authentication with app only credential flows.

When I try this method, the ULS logs always show a null UserIdentityName, and I receive an HTTP 403 back to the calling application. I have tried other methods with the same results. I am assuming I am missing some key piece of how EntraCP works as the claims provider, and am moving in the wrong direction.

Can anyone point me in the right direction to authenticate and use the SP REST API from another web app?

Non-OAuth request. IsAuthenticated=False, UserIdentityName=, ClaimsCount=0

(https://github.com/vgrem/Office365-REST-Python-Client?tab=readme-ov-file#Working-with-SharePoint-API)

**Comment by Yvand** [comment]
@tahawkins21, I looked at the documentation of the project: Unfortunately, the only authentication method that will work with SPS is [username and password](https://github.com/vgrem/Office365-REST-Python-Client#2-using-username-and-password), and that is only possible if SPS is configured with Windows authentication, it won't work with trusted authentication.

EntraCP cannot be of any help for this scenario
