### ISSUE TITLE
No SPClaimProvider created

### ISSUE THREAD

**Issue by FredAlma** [Yvand/EntraCP#234]
Hello Yvan,

Once the solution is deployed and the feature Online there is no SPClaimProvider created.

**Get-SPClaimProvider | ft DisplayName**

System
Active Directory
All Users
Forms Auth
User Profile Claim Provider

Both objects seems well deployed :

 **Get-SPSolution entracp.wsp**

Name                           SolutionId                           Deployed
----                           ----------                           --------
entracp.wsp                    dd03bdd7-0645-475e-a852-f180b8bc8191 True

**Get-SPFeature Yvand.EntraCP|select status, scope**

Status Scope
------ -----
Online  Farm

It is 2 servers farm where azureCP was deployed. I have tried to re-add, re-install, change server but nothing change ..

Have you any idea ?

Merci
Fred

**Comment by Yvand** [comment]
hi @FredAlma, after you depoyed the solution, you need to run this command:
`Install-SPFeature -SolutionId "dd03bdd7-0645-475e-a852-f180b8bc8191" -AllExistingFeatures`

FYI It is documented [here](https://entracp.yvand.net/docs/installation/), in the `manual install` tab.

**Comment by FredAlma** [comment]
Hi,

The feature was installed already (through the script you provide). After uninstall/reinstall the claims provider show up :

Uninstall-SPFeature 6633a7b5-1e36-4d3a-a091-cb30e1664f7a
Install-SPFeature -SolutionId "dd03bdd7-0645-475e-a852-f180b8bc8191" -AllExistingFeatures
Get-SPClaimProvider EntraCP

DisplayName                 : EntraCP
Description                 : EntraCP
IsEnabled                   : True
IsUsedByDefault             : True
IsVisible                   : True
AssemblyName                : Yvand.EntraCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636
TypeName                    : Yvand.EntraClaimsProvider.EntraCP
ClaimProvider               : Yvand.EntraClaimsProvider.EntraCP
ClaimProviderType           : Yvand.EntraClaimsProvider.EntraCP
IsValid                     : True
UpgradedPersistedProperties : {}

Great ! 
Fred
