### ISSUE TITLE
ULS Entries

### ISSUE THREAD

**Issue by Getoffmypatch** [Yvand/EntraCP#236]
While reviwing ULS logs relating to the deployment, I came across this entry. Please note that I didn't experience an issue - just trying to make sure that everything is set correctly.

[EntraCP] LogMsalError False MSAL 4.56.0.0 MSAL.Desktop 4.8 or later Windows Server 2016 Standard [2024-03-19 15:54:38Z - 550bdc97-571e-4fed-a4bb-11f39d67f3b1] Exception type: Microsoft.Identity.Client.MsalServiceException  , ErrorCode: invalid_client  HTTP StatusCode 401  CorrelationId 550bdc97-571e-4fed-a4bb-11f39d67f3b1     

[EntraCP] Unexpected error : Could not authenticate for tenant '<company>.onmicrosoft.com': MsalServiceException: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'c4793d8e-b292-48bf-8542-dd29a1d85f55'. Trace ID: 6effe6e7-3ad8-4402-bb16-1572e1b15100 Correlation ID: 550bdc97-571e-4fed-a4bb-11f39d67f3b1 Timestamp: 2024-03-19 15:54:38Z

Thanks,
Shane

**Comment by Yvand** [comment]
Hi @Getoffmypatch, the error message says:
`Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'c4793d8e-b292-48bf-8542-dd29a1d85f55'`

Are you actually able to get results from this tenant?

**Comment by Getoffmypatch** [comment]
Yes - I am getting results

![image](https://github.com/Yvand/EntraCP/assets/32172026/2bba74cf-7a6f-490a-bb60-169c1826ae9c)

**Comment by Getoffmypatch** [comment]
I removed the pre-existing AzureCP and redeployed EntraCP and that seems to have fixed it.

Thanks
