### ISSUE TITLE
Token acquisition fails when connecting to azure us gov Entra

### ISSUE THREAD

**Issue by RichCasale** [Yvand/EntraCP#245]
### Discussed in https://github.com/Yvand/EntraCP/discussions/244

<div type='discussions-op-text'>

<sup>Originally posted by **RichCasale** April  5, 2024</sup>
I have the latest version of EntraCP deployed on SharePoint SE (January CU) running on windows server 2022.  When I try and add my tenant configuration and I choose Azure US Government and the client secret I get a ULS error message...

Token Acquisition (1004) failed.  Host: login.microsoftonline.com.

...and another entry which states my Entra domain name cannot be found and to make sure I am signing into the correct cloud.  Even if I assign the tenant using PowerShell it still fails with the same message.  I am certain that my client secret works and I have run all the troubleshooting tests and they all pass when I use login.microsoft.us versus login.microsoft.com.

Is this a known issue or is there different set of commands that I need to use to get this to work.  This is a critical path component to a project I am working on for the gov so I would appreciate any help that can be sent my way.</div>

**Comment by Yvand** [comment]
@RichCasale I was not able to actually test to connect to a US tenant, because I don't have access to one.
Are you willing to allow me to try to connect to your tenant, so I can try this scenario?

If yes, I will send you my email to share the data privately

**Comment by RichCasale** [comment]
Unfortunately, I will not be able to provide access to our tenant since it’s is only available to customers of our internal backbone.  No external access is permitted.

I can share the following ULS log entries when I try to resolve a user.  (I changed our custom domain to our.tenant.gov).

04/05/2024 17:28:36.38                 w3wp.exe (0x3A2C)        0x22D4 EntraCP Azure Identity   1337       Medium                [EntraCP] LogMsalWarning False MSAL 4.56.0.0 MSAL.Desktop 4.8 or later Windows Server 2022 Datacenter [2024-04-05 17:28:36Z - c319b90a-04d3-4e72-937c-0b7db0b66bec] Request retry failed.

04/05/2024 17:28:36.38                 w3wp.exe (0x3A2C)        0x22D4 EntraCP Azure Identity   1337       High                [EntraCP] LogMsalError False MSAL 4.56.0.0 MSAL.Desktop 4.8 or later Windows Server 2022 Datacenter [2024-04-05 17:28:36Z - c319b90a-04d3-4e72-937c-0b7db0b66bec] === Token Acquisition (1004) failed.  Host: login.microsoftonline.com.

04/05/2024 17:28:36.38                 w3wp.exe (0x3A2C)        0x22D4 EntraCP Lookup 1337       Unexpected                [EntraCP] Unexpected error : Could not authenticate for tenant 'our.tenant.gov': MsalServiceException: AADSTS90002: Tenant 'our.tenant.gov' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant. Trace ID: e82a0b12-dcca-462e-b984-23c7e7df2600 Correlation ID: c319b90a-04d3-4e72-937c-0b7db0b66bec Timestamp: 2024-04-05 17:28:36Z

On your trouble shooting page you have this command:

Invoke-WebRequest -Uri https://login.microsoftonline.com -UseBasicParsing [-ProxyUseDefaultCredentials] [-Proxy http://127.0.0.1:8888]

This does not work from my tenant.  If I change the url to login.microsoftonlin.us, it works.

Also using this code block with my information works

$clientId = "<CLIENTID>"
$clientSecret = "<CLIENTSECRET>"
$tenantName = "<TENANTNAME>.onmicrosoft.com"
$headers = @{ "Content-Type" = "application/x-www-form-urlencoded" }
$body = "grant_type=client_credentials&client_id=$clientId&client_secret=$clientSecret&resource=https%3A//graph.microsoft.com/"
$response = Invoke-RestMethod https://login.microsoftonline.com/$tenantName/oauth2/token -Method "POST" -Headers $headers -Body $body [-ProxyUseDefaultCredentials] [-Proxy http://127.0.0.1:8888]
$response | ConvertTo-Json

This works correctly.  All the other test work correctly.


------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

**Comment by RichCasale** [comment]
Good morning.  After walking through your code with one of our developers while testing the connection, we noticed something that may actually be the culprit for the issue.

The code behind (Yvand.EntraCP/Yvand.EntraClaimsProvider/Configuration/EntraIDTenant.cs) begins the test at line 258.  This falls into a function just above for InitializeAuthentication.  In reviewing the initialize function, I see the hardcoded value on line 254 for the scope to be “graph.microsoft.com”.

In the documentation Microsoft Graph national cloud deployments - Microsoft Graph | Microsoft Learn<https://learn.microsoft.com/en-us/graph/deployments#microsoft-graph-and-graph-explorer-service-root-endpoints>, it states that GCC High uses “graph.microsoft.us” (the blue “important” callout box below the table).

Neither of us have all the tool pieces in place to compile this application (at this time).  So, I suggested that Rich reach back out to the developer and have him update line 254 to reflect:
                var scopes = new[] { “https://graph.microsoft.com/.default”, “https://graph.microsoft.us/.default” };

Would it be possible to get an updated build with the recommended changes?  I can download install and test and report back my finding.

Our testing concluded that it’s not related to login.microsoft.com vs .us, but rather verifying the access via the Graph call(s).

------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

From: Casale, Richard
Sent: Monday, April 8, 2024 12:35 PM
To: Yvand/EntraCP ***@***.***>; Yvand/EntraCP ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Yvand/EntraCP] Token acquisition fails when connecting to azure us gov Entra (Issue #245)

Unfortunately, I will not be able to provide access to our tenant since it’s is only available to customers of our internal backbone.  No external access is permitted.

I can share the following ULS log entries when I try to resolve a user.  (I changed our custom domain to our.tenant.gov).

04/05/2024 17:28:36.38                 w3wp.exe (0x3A2C)        0x22D4 EntraCP Azure Identity   1337       Medium                [EntraCP] LogMsalWarning False MSAL 4.56.0.0 MSAL.Desktop 4.8 or later Windows Server 2022 Datacenter [2024-04-05 17:28:36Z - c319b90a-04d3-4e72-937c-0b7db0b66bec] Request retry failed.

04/05/2024 17:28:36.38                 w3wp.exe (0x3A2C)        0x22D4 EntraCP Azure Identity   1337       High                [EntraCP] LogMsalError False MSAL 4.56.0.0 MSAL.Desktop 4.8 or later Windows Server 2022 Datacenter [2024-04-05 17:28:36Z - c319b90a-04d3-4e72-937c-0b7db0b66bec] === Token Acquisition (1004) failed.  Host: login.microsoftonline.com.

04/05/2024 17:28:36.38                 w3wp.exe (0x3A2C)        0x22D4 EntraCP Lookup 1337       Unexpected                [EntraCP] Unexpected error : Could not authenticate for tenant 'our.tenant.gov': MsalServiceException: AADSTS90002: Tenant 'our.tenant.gov' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud. Check with your subscription administrator, this may happen if there are no active subscriptions for the tenant. Trace ID: e82a0b12-dcca-462e-b984-23c7e7df2600 Correlation ID: c319b90a-04d3-4e72-937c-0b7db0b66bec Timestamp: 2024-04-05 17:28:36Z

On your trouble shooting page you have this command:

Invoke-WebRequest -Uri https://login.microsoftonline.com -UseBasicParsing [-ProxyUseDefaultCredentials] [-Proxy http://127.0.0.1:8888]

This does not work from my tenant.  If I change the url to login.microsoftonlin.us, it works.

Also using this code block with my information works

$clientId = "<CLIENTID>"
$clientSecret = "<CLIENTSECRET>"
$tenantName = "<TENANTNAME>.onmicrosoft.com"
$headers = @{ "Content-Type" = "application/x-www-form-urlencoded" }
$body = "grant_type=client_credentials&client_id=$clientId&client_secret=$clientSecret&resource=https%3A//graph.microsoft.com/"
$response = Invoke-RestMethod https://login.microsoftonline.com/$tenantName/oauth2/token -Method "POST" -Headers $headers -Body $body [-ProxyUseDefaultCredentials] [-Proxy http://127.0.0.1:8888]
$response | ConvertTo-Json

This works correctly.  All the other test work correctly.


------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

**Comment by Yvand** [comment]
@RichCasale thank you for sharing your analysis, this looks promising, and sorry for my late reply.
I will work on it asap, probably tomorrow, and update this thread.
Since I do not have access to a US Government, would you accept to test private builds of EntraCP (you should do that only on a test environment) and report the result?

**Comment by RichCasale** [comment]
No worries, I appreciate whatever attention you can provide.

We are only testing this in our lowest level environment for the time being so a one-off build would be fine for testing purposes.

Many thanks for your assistance on this.


------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

**Comment by Yvand** [comment]
@RichCasale I opened PR https://github.com/Yvand/EntraCP/pull/246 for this issue, and I just published a [nightly build](https://github.com/Yvand/EntraCP/releases/tag/nightly) that you can test in your environment.
To update your farm, please follow [this article](https://entracp.yvand.net/docs/usage/update/).

To set the authority for an existing tenant, you can use PowerShell:

```powershell
Add-Type -AssemblyName "Yvand.EntraCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [Yvand.EntraClaimsProvider.EntraCP]::GetConfiguration()
$settings = $config.Settings
# For a global tenant:
$settings.EntraIDTenants[0].AzureAuthority = New-Object System.Uri ("https://login.microsoftonline.com/")
# For a US-gov tenant:
$settings.EntraIDTenants[0].AzureAuthority = New-Object System.Uri ("https://login.microsoftonline.us/")
$config.ApplySettings($settings, $true)
```

The PR adds a new message in the log shows explicitly what authority / scope is used:

```
04/11/2024 09:58:40.00	powershell.exe (0x10C4)	0x20E4	EntraCP	Configuration	1337	High	[EntraCP] Initialized authentication for tenant "XXX.onmicrosoft.com" with authority "https://login.microsoftonline.com/" and scope "https://graph.microsoft.com/.default" .	5d832b90-b879-0001-c2a2-a7b0db8bda01
04/11/2024 09:58:40.00	powershell.exe (0x10C4)	0x20E4	EntraCP	Configuration	1337	High	[EntraCP] Initialized authentication for tenant "YYY.onmicrosoft.com" with authority "https://login.chinacloudapi.cn/" and scope "https://microsoftgraph.chinacloudapi.cn/.default" .	5d832b90-b879-0001-c2a2-a7b0db8bda01
```

If you want to call EntraCP directly using PowerShell, instead of the people picker, you can use this PowerShell script:

```powershell
Add-Type -AssemblyName ('Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c')
Add-Type -AssemblyName "Yvand.EntraCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$claimsProvider = New-Object Yvand.EntraClaimsProvider.EntraCP ("EntraCP")
$inputStr = "testEntraCPUser_001"
$context = New-Object System.Uri ("<SP WEB APP URL>")
[string[]] $entityTypes = @("User", "FormsRole")
$claimsProvider.Search($context, $entityTypes, $inputStr, $null, 30)
```

**Comment by RichCasale** [comment]
Awesome thank you.  I will get this deployed shortly and let you know the results.


------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

**Comment by RichCasale** [comment]
On the Troubleshoot EntraCP page in CA I’m getting this:

Test connection to 'https://login.microsoftonline.com' through proxy '': OK, took 333 ms.
Test connection to 'https://graph.microsoft.com' through proxy '': OK, took 1315 ms.
Test loading of dependencies: OK
Test connection to tenant 'ReplaceWithYourOwnValue' failed due to invalid credentials: ClientSecretCredential authentication failed: AADSTS900023: Specified tenant identifier 'replacewithyourownvalue' is neither a valid DNS name, nor a valid external domain. Trace ID: d30dc992-01c9-4e5c-80e3-cccb879e2b00 Correlation ID: b677aee2-e010-4df0-a0c8-edc533b2999f Timestamp: 2024-04-11 13:41:10Z

Maybe you didn’t update this page so I’m less concerned

I updated the solution per your web page.  I already have an existing tenant setup, so I ran…

$config = [Yvand.EntraClaimsProvider.EntraCP]::GetConfiguration()
$settings = $config.Settings
$settings.EntraIDTenants[0].AzureAuthority = New-Object System.Uri (https://login.microsoftonline.us/)
$config.ApplySettings($settings, $true)

I got similar errors as before so I removed the tenant and recreated it and I was able to do so via CA however in ULS I get errors.  Here are a couple of key ones.

[EntraCP] Initialized authentication for tenant "Mydomain.OnMicrosoft.us" using authority https://login.microsoftonline.us/ and scope https://graph.microsoft.us/.default .
[EntraCP] Graph returned error Unauthorized Unauthorized on request https://graph.microsoft.com/v1.0/$batch with JSON payload…




A couple of things:


  1.  I’d like to remove this conversation from your GitHub page since there is information that I cannot share in the open and this is hindering our process.
  2.  Would it be possible to schedule a screen share review of the errors I’m seeing so that you can see what I see.  I’m on the EST time zone however I’m willing to get on at any hour since I know you are based in France which is 6 hours ahead.
  3.  I feel like we’re getting very close.
  4.  A quick question, we’re using a custom <something>.<something>.<gov> Entra domain name.  WE do not use <something.onmicrosoft.us as our domain name.  In your tenant configuration should I be using the root tentant domain of onmicrosoft.us or can I put my full custom domain name in there?

------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

**Comment by Yvand** [comment]
I did additional research and my implementation is incomplete and needs a bit more work, I'll update you when it is ready (hopefully this week).
If after that it is still not working, yes we can connect directly.
I'm not sure what domain name you should type, but please note that it is totally fine to simply type the tenant ID instead, so you can use that if you are not sure.
I am not able to delete the issue, my only option is to close it. If you wish you can delete some of your comments

**Comment by RichCasale** [comment]
Ok that’s good to know, I’ll do my best to be patient.  😊  The fact that you’re willing to work with us on this I consider a gift so I won’t put any undue pressure on you.

If we can’t get it working though let’s sync up and maybe that will get us across the finish line.  I don’t need to tell you about the significance of your custom claims provider, so for it work correctly in the GCC High environment would be a big win for the code as well.

Also I haven’t shared anything sensitive at this point, I just know that what I’m omitting may actually help you debug.  😊

Thanks for your efforts.


------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

**Comment by Yvand** [comment]
I pushed a [new commit](https://github.com/Yvand/EntraCP/pull/246/commits/5a7d294755d2fc03999a42f2f11bac520e83292f) and I believe it will work much better.
I ended up by creating my own class to store the settings (authority and endpoints) per cloud instance, something I don't understand is not present by default in MSAL or Graph libraries.

Anyway, now tenants have a new property AzureCloud, where you can set the cloud instance.
Possible values are: `AzureGlobal (default), AzureChina, AzureUsGovernmentL4, AzureUsGovernmentL5`

To test this:

- Download the [new nightly release](https://github.com/Yvand/EntraCP/releases/tag/nightly)
- Update as documented [in this page](https://entracp.yvand.net/docs/usage/update/). The errors you got the last time when using PowerShell were not expected. After the update is complete, please make sure to close and open a new PowerShell process, to get the updated assemlies.
Side note: The messages in page TroubleshootEntraCP.aspx are totally expected, but I need to update the wording to clarify this
- Delete the tenant from EntraCP configuration and re-add it with your required cloud instance, either in the UI or PowerShell.

To add it in PowerShell with your required cloud instance:

```powershell
Add-Type -AssemblyName "Yvand.EntraCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [Yvand.EntraClaimsProvider.EntraCP]::GetConfiguration()
$settings = $config.Settings

$settings.EntraIDTenants.Clear()

# Add a new Azure AD tenant using a client secret
$tenant = New-Object "Yvand.EntraClaimsProvider.Configuration.EntraIDTenant"
$tenant.Name = "TENANT_NAME_OR_ID"
$tenant.SetCredentials("CLIENT_ID", "CLIENT_SECRET")
# New property to set the cloud instance. Possible values: AzureGlobal (default), AzureChina, AzureUsGovernmentL4, AzureUsGovernmentL5
$tenant.AzureCloud = [Yvand.EntraClaimsProvider.Configuration.AzureCloudName]::AzureUsGovernmentL4
$settings.EntraIDTenants.Add($tenant)

$config.ApplySettings($settings, $true)
```

**Comment by RichCasale** [comment]
Happy Monday to you. Quick update.  The update works, I’m able to resolve groups and users accounts from our Entra ID.   I’m still working on something at the moment that doesn’t seem right, but that may be on my end.  I’ll report back shortly with my final conclusion.

Thanks for all of your help.


------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

**Comment by Yvand** [comment]
Thank you for your feedback, please keep me posted

**Comment by RichCasale** [comment]
I think the component is working however my configuration between EntraCP and the OIDC-based trusted identity provider are out of alignment, because users assigned to SharePoint groups will not authenticate.  If I choose user identity as mail then it works but validate in people picker fails for external accounts.

To wrap this up, would it possible to schedule a screen session?

Please send me an email outside of the GitHub system so we can schedule something.

------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

**Comment by RichCasale** [comment]
Quick questions.  Is it possible to remove the EntraCP referenced in my trusted identity token issuer in SP, without blowing away the claim provider reference?

I want to test something without EntraCP being involved but I don’t want to blow it away.  Searches suggest I have to remove and recreate.


------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

From: Casale, Richard
Sent: Monday, April 15, 2024 2:21 PM
To: Yvand/EntraCP ***@***.***>; Yvand/EntraCP ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Yvand/EntraCP] Token acquisition fails when connecting to azure us gov Entra (Issue #245)

Happy Monday to you. Quick update.  The update works, I’m able to resolve groups and users accounts from our Entra ID.   I’m still working on something at the moment that doesn’t seem right, but that may be on my end.  I’ll report back shortly with my final conclusion.

Thanks for all of your help.


------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

**Comment by Yvand** [comment]
Yes, you can completely disconnect EntraCP from the SharePoint trust by running the script below:

```powershell
# Set private member m_ClaimProviderName to null. Note that using .NET reflection on SharePoint objects is not supported and you do this at your own risks
$trust = Get-SPTrustedIdentityTokenIssuer "<SPTRUST_NAME>"
$trust.GetType().GetField("m_ClaimProviderName", "NonPublic, Instance").SetValue($trust, $null)
$trust.Update()
```

Regarding your problem with guest accounts, I believe you can find the full explanation of this behavior in this article: https://learn.microsoft.com/en-us/entra/identity/saas-apps/sharepoint-on-premises-tutorial#manage-guest-users-access
Can you take a look?

**Comment by RichCasale** [comment]
Ah ha…

“to ensure that guest accounts are all identified with the same attribute, the identifier claims of the enterprise application should be updated to use the attribute user.localuserprincipalname instead of user.userprincipalname.”

I saw that article; however, we are using OIDC for authentication, so I glanced and then moved on.  Thank you for pointing this out.

Would these settings be appropriate?  I’ll change the claim type to http://schemas.xmlsoap.org/ws/2005/05/identity/claim/name - user.userprinciplename.
***@***.***
In the permissions mappings, do I change the claim type that is currently email address to “http://schemas.xmlsoap.org/ws/2005/05/identity/claim/name”?
***@***.***

------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

**Comment by RichCasale** [comment]
Forgive me apparently I’m not paying close enough attention today.  I just noticed that it says to change the identifier for guest users to UPN, so I’m good with that question.


------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

From: Casale, Richard
Sent: Wednesday, April 17, 2024 3:54 PM
To: Yvand/EntraCP ***@***.***>; Yvand/EntraCP ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Yvand/EntraCP] Token acquisition fails when connecting to azure us gov Entra (Issue #245)

Ah ha…

“to ensure that guest accounts are all identified with the same attribute, the identifier claims of the enterprise application should be updated to use the attribute user.localuserprincipalname instead of user.userprincipalname.”

I saw that article; however, we are using OIDC for authentication, so I glanced and then moved on.  Thank you for pointing this out.

Would these settings be appropriate?  I’ll change the claim type to http://schemas.xmlsoap.org/ws/2005/05/identity/claim/name - user.userprinciplename.
***@***.***
In the permissions mappings, do I change the claim type that is currently email address to “http://schemas.xmlsoap.org/ws/2005/05/identity/claim/name”?
***@***.***

------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

**Comment by Yvand** [comment]
There is no need to change any permission mapping in EntraCP, merely to update the user identifier for the guest accounts (in the global configuration page).
Note that, since you change the user identifier, previous permissions for guest users may no longer be working.
To test the effect of such a change in a reliable way, please always create a new site collection and test the new permissions there.

**Comment by RichCasale** [comment]
Yvand, wanted to give you a quick update that I’m working with Brent Person on the case I opened to get this working.  He has been a huge help.


------------------------------------------------
Rich Casale
ECM SharePoint Administrator
Enterprise Applications
Office of the Chief Information Officer
U.S. Department of the Treasury
Mobile: 843.819.6688 (Preferred)
***@***.******@***.***>

**Comment by Yvand** [comment]
Thank you for the heads-up, this is great, you are in good hands
