### ISSUE TITLE
Issue with EntraCP in SharePoint 2016 - assembly error

### ISSUE THREAD

**Issue by AbdulAfrad** [Yvand/EntraCP#250]
Unable to get access token for tenant 'tenant.onmicrosoft.com': Could not load file or assembly 'Azure.Core, Version=1.36.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The system cannot find the file specified.
Can someone please help me? I get this when I try to test connection.

**Comment by Yvand** [comment]
It looks like you did not set the assembly bindings, as documented in https://entracp.yvand.net/docs/usage/installation/#set-the-assembly-bindings

**Comment by AbdulAfrad** [comment]
Hi Yvand,
That was it. appreciate it.
another question how can I map SharePoint user domainname\username with Entra ID UPN or email address?

Regards

**Comment by Yvand** [comment]
You cannot. Users who sign-in to SharePoint with different authentication modes are completely different and cannot be mapped.
You either need to duplicate permissions (bad idea, almost impossible to maintain) or use only 1 mode and migrate the permissions of the old mode to the new mode
