### ISSUE TITLE
Is ExcludeMemberUsers parameter still valid in EntraCP ?

### ISSUE THREAD

**Issue by CSART69** [Yvand/EntraCP#255]
Hi
I used the setting "ExcludeMemberUsers" to exclude internal members synchronized to Azure in the people picker.
I've defined it in powershell as described in issue 44 but it seems that it does not work in the last version of EntraCP.
Is it still configurable in EntraCP (as it was in AzureCP) ?
Many thanks
Best regards
Christophe S.

**Comment by Yvand** [comment]
Hi, I just tested the property and it works fine according to my tests.
Is the property set correctly when you run this script:

```powershell
Add-Type -AssemblyName "Yvand.EntraCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [Yvand.EntraClaimsProvider.EntraCP]::GetConfiguration()
$config.Settings.EntraIDTenants[0]
```

**Comment by Yvand** [comment]
LDAPCPSE does not cache any result, but SharePoint does cache previous people picker results that were added to the site, so it might be that indeed
