### ISSUE TITLE
Unable to map Firstname,lastname and email from Entra ID to SharePoint 2016

### ISSUE THREAD

**Issue by AbdulAfrad** [Yvand/EntraCP#257]
Hello,
Like to see Firstname,lastname and email address when I view user profile

Name	Test Broker3
**Work email**	 
Mobile phone	123456789
About me	
 
Picture	 
Department	 
Title	 
SIP Address	 
**First name**	 
**Last name**	 
Work phone	 
**User name**	 

Please let me know how can I achieve this?
Thank you

**Comment by Yvand** [comment]
Hi @AbdulAfrad, a claims provider such as EntraCP does not influence how data are displayed in the profile of a user, assuming you are talking about the User Profile Service

**Comment by AbdulAfrad** [comment]
Hi @Yvand 
It is out of topic question but need your help here.
I have a SharePoint 2016 farm with a web app with multiple externally shared site collection. Current user id is 
	*_*i:0#.w|DomainName \testuser1** but we are going Windows Auth to Microsoft Entra ID for customers. There are about 10k existing users with different kind of permissions site, subsite,lists and libraries. I need to get user to access the site user id should be like **i:0e.t|microsoftentratrust|testuser3@externalidtest.onmicrosoft.com**


Based on this article https://adamsorenson.com/sharepoint-20132016-migrate-from-windows-claims-to-adfs/
looks like I need to use The -IdentifierClaimIs can only be ACCOUNT-NAME, EMAIL, or USER-PRINCIPAL-NAME.
with   -UseDefaultConfiguration parameter . I can create one but for some reason I cannot login if I create this way but
I follow this MS https://learn.microsoft.com/en-us/entra/identity/saas-apps/sharepoint-on-premises-tutorial#configure-the-enterprise-application I can login but cannot convert user and group. get the below error:
C**onvert-SPWebApplication : SAML based claim authentication is not compatible.**

This is how I created:
$trust = New-SPTrustedIdentityTokenIssuer -Name "MicrosoftEntraTrust" -Description "Microsoft Entra ID" -Realm $realm -ImportTrustCertificate $signingCert -ClaimsMappings $userIdentifier, $role -SignInUrl $loginUrl -IdentifierClaim $userIdentifier.InputClaimType
The SPTrustedLoginProvider 'MicrosoftEntraTrust' is set with identity claim type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn', but is not set in claim types configuration list.
Please visit claim types configuration page to add it.
###   EntraCP:
**This table shows the mappings between the claim types (initially defined in SPTrustedIdentityTokenIssuer "microsoftentratrust") and the Microsoft Entra ID objects and properties.**
Actions	Claim type	Microsoft Entra ID object details	Optional settings
Object type	Property to query	Property to display	PickerEntity metadata	Prefix to bypass lookup
Edit  Delete  	http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress	User	UserPrincipalName			
Delete  	Microsoft Entra ID property linked to the main mapping for object User	User	DisplayName		DisplayName	
Delete  	Microsoft Entra ID property linked to the main mapping for object User	User	GivenName			
Delete  	Microsoft Entra ID property linked to the main mapping for object User	User	Surname			
Delete  	Microsoft Entra ID property linked to the main mapping for object User	User	Mail		Email	
Delete  	Microsoft Entra ID object property linked to a PickerEntity metadata	User	MobilePhone		MobilePhone	
Delete  	Microsoft Entra ID object property linked to a PickerEntity metadata	User	JobTitle		Title	
Delete  	Microsoft Entra ID object property linked to a PickerEntity metadata	User	Department		Department	
Delete  	Microsoft Entra ID object property linked to a PickerEntity metadata	User	OfficeLocation		Location	
Edit  Delete  	http://schemas.microsoft.com/ws/2008/06/identity/claims/role	Group	Id	DisplayName		
Delete  	Microsoft Entra ID property linked to the main mapping for object Group	Group	DisplayName		DisplayName	
Delete  	Microsoft Entra ID object property linked to a PickerEntity metadata	Group	Mail		Email	

Entra ID:
Attributes & Claims
Required claim
Claim name
Type
Value
Unique User Identifier (Name ID)
SAML
user.localuserprincipalname [nameid-format:emailAddress]
Additional claims
Claim name
Type
Value
FirstName
SAML
user.givenname
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
SAML
user.localuserprincipalname
LastName
SAML
user.surname

Please help me here. Thank you in advance.

**Comment by Yvand** [comment]
To migrate user permissions, do NOT use `Convert-SPWebApplication` and do NOT run `New-SPTrustedIdentityTokenIssuer` with the switch `-UseDefaultConfiguration`. EntraCP cannot work with this setting.

Instead, to migrate the permission of 1 user, farm-wide, from Windows to Trusted authentication, you should use the script below:

```powershell
$oldlogin="i:0#.w|DomainName\testuser1"
$newlogin="i:0e.t|microsoftentratrust|testuser3@externalidtest.onmicrosoft.com"
[Microsoft.SharePoint.Administration.SPFarm]::Local.MigrateUserAccount($oldlogin, $newlogin, $false)
```

**Comment by AbdulAfrad** [comment]
First of all, a big thank you.
Q1: will it retain the existing permission?
Q2: Do I need to export all users to a CSV file and run- from CSV? please let me know

**Comment by Yvand** [comment]
No, the script moves the permissions of a given account, to a new account, it does not copy or duplicate them.
You can use exactly the same script to move groups
`Move-SPUser` calls `SPFarm.MigrateUserAccount` behind the scene. Personally I find `SPFarm.MigrateUserAccount` much easier to use since you explicitly specify 2 string parameters.
There is no easy way to migrate permissions in just a web app. If you want to migrate only a web app, a good approach is to run the script in a temp farm where you restored the content db of that web app

**Comment by AbdulAfrad** [comment]
Thank you.
well, Same account has access to the different Web App in the same farm, but I do not want convert user for all web apps but specific one.
Q: Any Clue why I cannot add Entra ID user to a new site collection created under a web app configured for Entra ID?
Q: what kind of issues you faced why using Move-SPUser  command?

Appreciate your help.

**Comment by Yvand** [comment]
To determine why youcannot add an Entra ID user to a new site collection created under a web app configured for Entra ID, you can check the SharePoint logs and filter on product/area EntraCP, it should explain why the user is not returned
