### ISSUE TITLE
Sharing failed: Couldn't resolve user

### ISSUE THREAD

**Issue by laurentkai** [Yvand/EntraCP#260]
Hello,

I'm evaluating EntraCP and I'm facing a issue when Sharing with someone from Entra ID.
EntraCP is correctly resolving users from EntraID, however when clicking on "Share" I'm getting the error : Couldn't Resolve User.
Sharing with Guests from EntraId is working fine.
Am I missing something ?

Regards,

![Pasted image 20240527092617](https://github.com/Yvand/EntraCP/assets/28298011/0ef35a4b-7c12-4da0-9ab4-e8f507727886)

![Pasted image 20240527091925](https://github.com/Yvand/EntraCP/assets/28298011/1faafa57-a3ec-4dbf-a18b-6c62f52cd320)

**Comment by Yvand** [comment]
Can you check the SharePoint logs and filter on product/area `EntraCP` ? It should help to understand why the validation fails

**Comment by laurentkai** [comment]
> Can you check the SharePoint logs and filter on product/area `EntraCP` ? It should help to understand why the validation fails

Hi Yvan,
Here are events from the ULS : 
[EntraCPError.txt](https://github.com/Yvand/EntraCP/files/15454013/EntraCPError.txt)

![image](https://github.com/Yvand/EntraCP/assets/28298011/5ba0ee9d-2fc1-4aeb-86dd-d958dde2c1c0)
