### ISSUE TITLE
No users found in People Picker

### ISSUE THREAD

**Issue by pwann** [Yvand/EntraCP#261]
Hi.

I have installed EntraCP on my SharePoint solution and connected it to Microsoft Entra as per the documentation.

When I check the "Troubleshoot EntraCP" page, it is correctly connecting to the tenant and finding users that are registered in Entra. But when I try to find users via the People Picker no results are returned. Am I missing some People Picker configuration that is not in the documentation?

I checked the EntraCP logs and nothing is throwing any errors, but it's only logging the user I was searching for when on the troubleshooting page.

![image](https://github.com/Yvand/EntraCP/assets/150549437/c56fcbf9-1d15-40c2-998c-1dc530061081)

**Comment by Yvand** [comment]
Can you check the SharePoint logs and filter on product/area "EntraCP" while you use the people picker?
It will return the activity of the claims provider

**Comment by pwann** [comment]
Hi Yvand. Thanks for the response :)

This is what is being logged; however, it only logs when the "Troubleshoot EntraCP" page is refreshed in Central Adminitration. When using the People Picker, nothing is logged. It seems as though it's not connected to the People Picker at all, if that makes sense.

![image](https://github.com/Yvand/EntraCP/assets/150549437/6ff92b61-232f-4348-9ad5-f5246246c2c1)

**Comment by Yvand** [comment]
Hi @pwann, for EntraCP to be used in the people picker, you have to use the people picker from any zone in a web application that uses the trusted authentication EntraCP is connected with.

**Comment by pwann** [comment]
Hi @Yvand

Thanks the help. I was able to fix it by giving the web application administrator rights.
