### ISSUE TITLE
Unable to setup Alerts in SharePoint 2016

### ISSUE THREAD

**Issue by ameymulay** [Yvand/EntraCP#263]
The logging in the site works fine using my email address using Entra.
However, when I try to setup alerts it displays the error :
You do not have an e-mail address.
Alert has been created successfully but you will not receive notifications until valid e-mail or mobile address has been provided in your profile
If we check the profile the Work Email is blank.
Following are my mappings :
<img width="671" alt="image" src="https://github.com/Yvand/EntraCP/assets/34329182/493a68d3-1ce9-4a42-882b-fc0ce4e0b677">

**Comment by ameymulay** [comment]
SharePoint log error :

Context has no SMTP/UPN claims.

**Comment by Yvand** [comment]
Sorry for my late reply.
I see that the mapping for the email is set, but it is not enough.
You need to consider the following points:
- The service that should supply the email of users is the User Profile Service
- A custom claims provider like EntraCP may provide the email, but SharePoint will actually use it ONLY if:
  - The user is added to the site collection for the very 1st time
  - And until the User Profille Service job runs and overwrites it

To convince yourself of this, try to create a brand new site collection and setup the alerts here
