### ISSUE TITLE
An exception occurred in EntraCP claim provider when calling SPClaimProvider.FillHierarchy(): Thread was being aborted

### ISSUE THREAD

**Issue by fqzy826** [Yvand/EntraCP#268]
We host a SharePoint subscription edition farm and the web application has two zones.  The default zone use windows authentication and the internet zone integrated with Azure AD with SMAL

The EntraCP version is 22.020230927

The issue is when end user access the internet zone and try to sharing something, the people picker will have error "Sorry, we're having trouble reaching the server" after around 1 minute waiting. This happens to all end user assessing from internet zone.  
But if I access the same site with the default zone URL on the server, the people picker works fine.

The workaround is doing an IIS Reset on all WFE servers and it seems fixed this issue.

This issue happened a few times and seems quite random. 

In the event, we can see the Event ID 8307 with the error
An exception occurred in EntraCP claim provider when calling SPClaimProvider.FillHierarchy(): Thread was being aborted

**Comment by Yvand** [comment]
@fqzy826 this is a known issue that is fixed in v23.0
You should update to latest version

**Comment by fqzy826** [comment]
Many thanks, the issue fixed after the update.
