### ISSUE TITLE
Configuration of EntraCP "Yvand.EntraCP V25.0.20240503.33"

### ISSUE THREAD

**Issue by RamParamesh** [Yvand/EntraCP#270]
We host a SharePoint subscription edition and currently using AzureCP authentication. Since Azure CP was deprecated, we are configuring EntraCP version: V25.0.20240503.33. We have the below 2 queries when we follow the blog:https://entracp.yvand.net/docs/usage/installation/

Query1: To configure Proxy for EntraCP, which IP address we need to provide for PROXY Address in the below step:
Add-Type -AssemblyName "Yvand.EntraCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [Yvand.EntraClaimsProvider.EntraCP]::GetConfiguration()
$settings = $config.Settings
**$settings.ProxyAddress = "http://localhost:8888"**
$config.ApplySettings($settings, $true)
Please also see the screenshot for reference

![image](https://github.com/Yvand/EntraCP/assets/173476401/2d4606c7-9697-4a73-b846-ce0e6722a5e1)

Query2:	When we are adding Microsoft Entra ID using Client Secret instead of Certificate, do we need to follow the below process mention in the blog. 
Configure the proxy for certificate validation[#](https://entracp.yvand.net/docs/how-to/configure-the-proxy/#configure-the-proxy-for-certificate-validation)

Screenshot below for reference:
![image](https://github.com/Yvand/EntraCP/assets/173476401/60e163b7-eebe-4f43-8649-1756177c2968)

Please provide the response asap, as we have an ongoing issue in the PRODUCTION environment which is using AzureCP authentication. We are looking to replace AzureCP with EntraCP at the earliest

**Comment by Yvand** [comment]
I cannot tell you the IP of your proxy, it completely depends on your environment, if you use a proxy at all.
If the SharePoint servers have a direct access to internet, then you don't use a proxy and you don't need to set it.

Note that it is totally unrelated with the client certificate / client secret you set for the tenant

**Comment by RamParamesh** [comment]
Hi Yvand, Appreciate your quick responses earlier. Please provide your suggestion on below:

We host a SharePoint subscription edition and currently using AzureCP authentication. Since AzureCP was deprecated, we are planning to configure- EntraCP version: V25.0.20240503.33.

Please suggest if we need to completely remove the AzureCP solution from the SharePoint Farm and then proceed with EntraCP? (or) Can we configure EntraCP keeping Azure CP(not uninstalling the solution but removing as a trusted identity provider from sharepoint).

Will it cause any issues in future if we keep both AzureCP and EntraCP in the farm but only use EntraCP?

**Comment by Yvand** [comment]
@RamParamesh it is not mandatory to remove AzureCP, but I recommend that you [properly uninstall it](https://entracp.yvand.net/docs-azurecp/usage/remove/#uninstall-azurecp) before deploying EntraCP.
Note that both solutions are independent and can run at same time on the farm

**Comment by RamParamesh** [comment]
Hi Yvand,

We would like to know if there will be any kind of standby support during golive in our environment for EntraCP to assist us incase of any issues.

Please let me know if it is possible to raise any support case with Github for the same. If so, please guide me with the process.

**Comment by Yvand** [comment]
@RamParamesh sorry no, EntraCP is not a commercial product.
It is a completely free, open source project, essentially developped by me, and I do not do it for money.

If you have a problem, feel free to open an issue in the GitHub project, like you did here, and I will do my best to help, but I cannot commit to any sort of engagement
