### ISSUE TITLE
People Picker not working in Central Administration

### ISSUE THREAD

**Issue by pwann** [Yvand/EntraCP#284]
The people picker works fine in the web application, but does not work in Central Administration. This is an issue since we cannot give admin permissions to users from Microsoft Entra.

Do anybody know how to fix this issue?

**Comment by pwann** [comment]
Small update:

When I switch Claim Provider on trust back to AzureCP it works without issue

**Comment by Yvand** [comment]
hi @pwann, can you give more details exactly when you mention that EntraCP is not working in central administration?
Can you check the SharePoint logs and filter on product/area "EntraCP" to see if there is any error?

**Comment by pwann** [comment]
Hi Yvand

Sorry for the late reply, but the problem has now been fixed. The ULS logs showed errors regarding assembly references, so I updated the web.config for Central Administration, and it started working as intended.
